server:
  port: 8801
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/project/spring-cloud-start/config-repo
          search-paths: dev
      label: master

