server:
  port: 8801
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/gongshw1992/spring-cloud-prototype
          search-paths: conf/dev
      label: master

