spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: >-
      jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/db
      ?useUnicode=true
      &characterEncoding=utf-8
      &serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
base:
  auth:
    excludes: ['/v1/time', '/v1/list']
mybatis:
  configuration:
    map-underscore-to-camel-case: true
