#!/usr/bin/env bash

applications=`find . -name build.gradle\
    |xargs grep "gradle/include/bootstrap.gradle"\
    |sed -E 's/^\.\/(.+)\/build.gradle:.*$/\1/p'\
    |sed -E 's/\//:/g'\
    |uniq`

for app in ${applications}
do
    $@ ${app} || exit 1
done
